[phases.setup]
nixPkgs = ['python311', 'libGL', 'glib', 'libsm', 'libxrender', 'libxext']

[phases.install]
cmds = ['pip install --upgrade pip', 'pip install -r requirements.txt']

[start]
cmd = 'uvicorn app:app --host 0.0.0.0 --port $PORT'
